; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
board_build.filesystem = littlefs
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
	adafruit/Adafruit GFX Library@^1.11.11
	zinggjm/GxEPD2@^1.6.1
	olikraus/U8g2_for_Adafruit_GFX@^1.8.0
	bblanchon/ArduinoJson@^7.3.0
	paulstoffregen/Time@^1.6.1
	arduino-libraries/NTPClient@^3.2.1
build_flags = 
	-DU8G2_WITH_SMALL_FONT
	-DU8G2_WITH_UNICODE
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
